version: 2

sources:
  - name: raw_data        
    schema: raw_data       
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_items
      - name: order_payments
      - name: sellers
      - name: order_reviews
      - name: geolocation
      - name: product_category_name_translation

      
    
